/* نقطة دخول حزمة التشخيص V2 */
export { DiagnosticEngineV2, createEngineV2, CONFIRMATION_MIN_QUESTIONS, CONFIRMATION_MAX_QUESTIONS } from './engine'
export type { RecommendationV2 } from './engine'
export { derivePersona, personaLabelAr, basePersonaCode } from './personas'
export { assessDomains } from './domains'
export { buildSkillStates, assessPathwaySkills } from './skills'
export { assessPathwayEligibility, eligibleQuestionsV2, isQuestionEligible } from './eligibility'
export { scoreEligiblePathways } from './score'
export { computeConfidenceV2, OUTPUT_THRESHOLDS } from './confidence'
export { CORE_SEQUENCE, V2_STOP } from './select'
export { buildExplanation } from './explain'
export { buildAdvisorHandoff } from './handoff'
export { excludedGoalOptions, reinterpretGoalForPersona } from './goals'
export * from './types'
